//
//  FoundationModelsAskUseCase.swift
//  SafeSeasons
//
//  SRP: Q&A via Apple Foundation Models when available. No tools—Foundation Model answers everything.
//  Compiles only when FoundationModels SDK is available (e.g. Xcode 26 / iOS 26).
//

#if canImport(FoundationModels)

import Foundation
import FoundationModels

@available(iOS 26.0, *)
final class FoundationModelsAskUseCase: AskSafeSeasonsUseCaseProtocol, @unchecked Sendable {

    init() {}

    func isAppleIntelligenceAvailable() -> Bool {
        switch SystemLanguageModel.default.availability {
        case .available: return true
        case .unavailable: return false
        @unknown default: return false
        }
    }

    /// Answer is always generated by the Apple Foundation Model via session.respond(to: question).
    /// No tools—we supply instructions and context; the model answers everything from its knowledge.
    func ask(question: String, context: AskContext) async throws -> String {
        guard isAppleIntelligenceAvailable() else {
            throw AskError.appleIntelligenceUnavailable
        }

        let instructions = buildInstructions(context: context)
        let session = LanguageModelSession(instructions: instructions)

        let options = GenerationOptions(
            sampling: .greedy,
            temperature: 0.6,
            maximumResponseTokens: 512
        )
        let response = try await session.respond(to: question, options: options)
        return response.content
    }

    
    private func buildInstructions(context: AskContext) -> String {
        let base = loadBundledInstructions()
        let contextBlock: String
        if let state = context.state {
            contextBlock = "User's location: \(state.name) (\(state.abbreviation)). Current month: \(context.month). Common hazards: \(state.topHazards.joined(separator: ", ")).\n\n"
        } else {
            contextBlock = "User has not selected a state. Current month: \(context.month).\n\n"
        }
        return contextBlock + base
    }

    private func loadBundledInstructions() -> String {
        if let url = Bundle.main.url(forResource: "ask_instructions", withExtension: "txt", subdirectory: "Data"),
           let data = try? Data(contentsOf: url),
           let text = String(data: data, encoding: .utf8), !text.isEmpty {
            return text
        }
        if let url = Bundle.main.url(forResource: "ask_instructions", withExtension: "txt"),
           let data = try? Data(contentsOf: url),
           let text = String(data: data, encoding: .utf8), !text.isEmpty {
            return text
        }
        return "You are SafeSeasons, a disaster preparedness assistant. Answer from your knowledge. Use clear spacing and newlines. For life-threatening emergencies say to call 911."
    }
}

enum AskError: Error {
    case appleIntelligenceUnavailable
}

#endif
