//
//  FoundationModelsAskUseCase.swift
//  DisasterReady
//
//  SRP: Q&A via Apple Foundation Models when available. No tools—Foundation Model answers everything.
//  Compiles only when FoundationModels SDK is available (e.g. Xcode 26 / iOS 26).
//

#if canImport(FoundationModels)

import Foundation
import FoundationModels

@available(iOS 26.0, *)
final class FoundationModelsAskUseCase: AskDisasterReadyUseCaseProtocol, @unchecked Sendable {

    init() {}

    func isAppleIntelligenceAvailable() -> Bool {
        switch SystemLanguageModel.default.availability {
        case .available: return true
        case .unavailable: return false
        @unknown default: return false
        }
    }

    /// Answer is always generated by the Apple Foundation Model via session.respond(to: question).
    func ask(question: String, context: AskContext) async throws -> String {
        guard isAppleIntelligenceAvailable() else {
            throw AskError.appleIntelligenceUnavailable
        }

        let instructions = buildInstructions(context: context)
        let session = LanguageModelSession(instructions: instructions)

        do {
            let response = try await session.respond(
                to: question,
                options: GenerationOptions(temperature: 0.6, maximumResponseTokens: 900)
            )
            return response.content
        } catch let error as LanguageModelSession.GenerationError {
            return handleGenerationError(error)
        }
    }

    private func handleGenerationError(_ error: LanguageModelSession.GenerationError) -> String {
        switch error {
        case .guardrailViolation:
            return "For your safety, I can't generate that specific content. If you're experiencing a medical emergency, please call 911 immediately. I'm here to help with disaster preparedness — ask me about storms, emergency kits, evacuation plans, and more!"
        case .refusal:
            return "I wasn't able to respond to that directly. If you have a health concern, please contact your doctor or call 911 for emergencies. For disaster preparedness and safety tips — I'm ready to assist!"
        case .exceededContextWindowSize:
            return "That question was too long. Could you try a shorter question? Example: \"How do I prepare for a hurricane?\""
        case .assetsUnavailable:
            return "Apple Intelligence is still downloading. Please try again in a few minutes."
        case .unsupportedLanguageOrLocale:
            return "I currently only support U.S. English. Please try in English."
        case .decodingFailure:
            return "I had trouble processing that. Could you rephrase your question?"
        case .rateLimited, .concurrentRequests:
            return "I'm a bit busy right now. Please try again in a moment."
        case .unsupportedGuide:
            return "I encountered an internal issue. Please try a different question."
        @unknown default:
            return "Something went wrong. Please try again."
        }
    }

    
    private func buildInstructions(context: AskContext) -> String {
        let base = loadBundledInstructions()
        let contextBlock: String
        if let state = context.state {
            contextBlock = "User's location: \(state.name) (\(state.abbreviation)). Current month: \(context.month). Common hazards: \(state.topHazards.joined(separator: ", ")).\n\n"
        } else {
            contextBlock = "User has not selected a state. Current month: \(context.month).\n\n"
        }
        return contextBlock + base
    }

    private func loadBundledInstructions() -> String {
        if let url = Bundle.main.url(forResource: "ask_instructions", withExtension: "txt", subdirectory: "Data"),
           let data = try? Data(contentsOf: url),
           let text = String(data: data, encoding: .utf8), !text.isEmpty {
            return text
        }
        if let url = Bundle.main.url(forResource: "ask_instructions", withExtension: "txt"),
           let data = try? Data(contentsOf: url),
           let text = String(data: data, encoding: .utf8), !text.isEmpty {
            return text
        }
        return "You are DisasterReady, a disaster preparedness assistant. Answer from your knowledge. Use clear spacing and newlines. For life-threatening emergencies say to call 911."
    }
}

enum AskError: Error {
    case appleIntelligenceUnavailable
}

#endif
