

#if canImport(FoundationModels)

import Foundation
import FoundationModels

@available(iOS 26.0, *)
@Generable
private struct GenerablePreparednessPlan: Equatable {
    let disasterType: String
    let steps: [String]
    let supplies: [String]
    let urgencyLevel: String
}

@available(iOS 26.0, *)
@Generable
private struct GenerablePersonalizedChecklistItem: Equatable {
    let name: String
    let priority: String
    let reason: String
}

@available(iOS 26.0, *)
@Generable
private struct GenerablePersonalizedChecklist: Equatable {
    let items: [GenerablePersonalizedChecklistItem]
}

@available(iOS 26.0, *)
@Generable
private struct GenerableQuestionClassification: Equatable {
    let disasterType: String?
    let mentionedState: String?
    let urgency: String
}

@available(iOS 26.0, *)
@Generable
private struct GenerableQuestionRoute: Equatable {
    let category: String
    let confidence: Double
    let suggestedData: String?
}

@available(iOS 26.0, *)
@Generable
private struct GenerablePrioritizedAction: Equatable {
    let step: String
    let priority: String
    let estimatedTime: String?
}

@available(iOS 26.0, *)
@Generable
private struct GenerablePrioritizedActions: Equatable {
    let actions: [GenerablePrioritizedAction]
}

@available(iOS 26.0, *)
@Generable
private struct GenerablePreparednessQuery: Equatable {
    let disasterType: String?
    let state: String?
    let month: String?
    let queryType: String
}

@available(iOS 26.0, *)
@Generable
private struct GenerableUserQueryExtraction: Equatable {
    let mentionedState: String?
    let mentionedDisaster: String?
    let timeReference: String?
    let questionType: String
}

@available(iOS 26.0, *)
@Generable
private struct GenerableDisasterVisualPrompt: Equatable {
    @Guide(description: "A sanitized, artistic description for image generation. Do NOT include people, faces, or identities. Focus on weather, atmosphere, setting, and inanimate elements. Safe for work. Under 2 sentences.")
    var prompt: String
}



@available(iOS 26.0, *)
private extension PreparednessPlan {
    init(from generable: GenerablePreparednessPlan) {
        self.init(
            disasterType: generable.disasterType,
            steps: generable.steps,
            supplies: generable.supplies,
            urgencyLevel: generable.urgencyLevel
        )
    }
}

@available(iOS 26.0, *)
private extension PersonalizedChecklistItem {
    init(from generable: GenerablePersonalizedChecklistItem) {
        self.init(
            name: generable.name,
            priority: generable.priority,
            reason: generable.reason
        )
    }
}

@available(iOS 26.0, *)
private extension PersonalizedChecklist {
    init(from generable: GenerablePersonalizedChecklist) {
        self.init(
            items: generable.items.map { PersonalizedChecklistItem(from: $0) }
        )
    }
}

@available(iOS 26.0, *)
private extension QuestionClassification {
    init(from generable: GenerableQuestionClassification) {
        self.init(
            disasterType: generable.disasterType,
            mentionedState: generable.mentionedState,
            urgency: generable.urgency
        )
    }
}

@available(iOS 26.0, *)
private extension QuestionRoute {
    init(from generable: GenerableQuestionRoute) {
        self.init(
            category: generable.category,
            confidence: generable.confidence,
            suggestedData: generable.suggestedData
        )
    }
}

@available(iOS 26.0, *)
private extension PrioritizedAction {
    init(from generable: GenerablePrioritizedAction) {
        self.init(
            step: generable.step,
            priority: generable.priority,
            estimatedTime: generable.estimatedTime
        )
    }
}

@available(iOS 26.0, *)
private extension PrioritizedActions {
    init(from generable: GenerablePrioritizedActions) {
        self.init(
            actions: generable.actions.map { PrioritizedAction(from: $0) }
        )
    }
}

@available(iOS 26.0, *)
private extension PreparednessQuery {
    init(from generable: GenerablePreparednessQuery) {
        self.init(
            disasterType: generable.disasterType,
            state: generable.state,
            month: generable.month,
            queryType: generable.queryType
        )
    }
}

@available(iOS 26.0, *)
private extension UserQueryExtraction {
    init(from generable: GenerableUserQueryExtraction) {
        self.init(
            mentionedState: generable.mentionedState,
            mentionedDisaster: generable.mentionedDisaster,
            timeReference: generable.timeReference,
            questionType: generable.questionType
        )
    }
}

// MARK: - Foundation Models Extended Features Implementation
// Uses Foundation Models for full on-device text generation (not Core ML tagging/extraction only).
// When Apple Intelligence is available, Ask DisasterReady answers are generated by the language model.

@available(iOS 26.0, *)
final class FoundationModelsExtendedFeatures: ExtendedAskDisasterReadyUseCaseProtocol,
                                               GuidedGenerationUseCaseProtocol,
                                               ContentTaggingUseCaseProtocol,
                                               SummarizationUseCaseProtocol,
                                               EmergencyPrioritizationUseCaseProtocol,
                                               QueryParsingUseCaseProtocol,
                                               ConversationSessionProtocol,
                                               @unchecked Sendable {
    
    private let sessionLock = NSLock()
    private var _conversationSession: LanguageModelSession?
    private var _conversationTranscript: Transcript?
    private var _prewarmSession: LanguageModelSession?    // Held alive so prewarm isn't discarded
    
    private var conversationSession: LanguageModelSession? {
        get { sessionLock.withLock { _conversationSession } }
        set { sessionLock.withLock { _conversationSession = newValue } }
    }
    private var conversationTranscript: Transcript? {
        get { sessionLock.withLock { _conversationTranscript } }
        set { sessionLock.withLock { _conversationTranscript = newValue } }
    }
    
    init() {}
    

    
    private func makeSession(context: AskContext? = nil) -> LanguageModelSession {
        let instructions = buildInstructions(context: context)
        return LanguageModelSession(instructions: instructions)
    }
    

    
    func isAppleIntelligenceAvailable() -> Bool {
        switch SystemLanguageModel.default.availability {
        case .available: return true
        case .unavailable: return false
        @unknown default: return false
        }
    }
    
    func ask(question: String, context: AskContext) async throws -> String {
        guard isAppleIntelligenceAvailable() else {
            throw FoundationModelsError.appleIntelligenceUnavailable
        }
        
        let session = makeSession(context: context)
        
        do {
            let response = try await session.respond(
                to: question,
                options: GenerationOptions(temperature: 0.6, maximumResponseTokens: 900)
            )
            return response.content
        } catch let error as LanguageModelSession.GenerationError {
            return handleGenerationError(error)
        }
    }
    
   
    
    func streamAsk(question: String, context: AskContext) -> AsyncThrowingStream<String, Error> {
        AsyncThrowingStream { continuation in
            Task {
                do {
                    guard isAppleIntelligenceAvailable() else {
                        continuation.finish(throwing: FoundationModelsError.appleIntelligenceUnavailable)
                        return
                    }
                    
                    let session = makeSession(context: context)
                    
                    let prompt = Prompt { question }
                    let stream = session.streamResponse(
                        to: prompt,
                        options: GenerationOptions(temperature: 0.6, maximumResponseTokens: 900)
                    )
                    
                    // Handle cumulative streaming: Foundation Models returns full response so far, not incremental chunks
                    var previousContent = ""
                    
                    for try await partial in stream {
                        let currentContent = partial.content
                        
                        // If current content starts with previous, it's cumulative - extract new part only
                        if currentContent.hasPrefix(previousContent) && currentContent.count > previousContent.count {
                            var newChunk = String(currentContent.dropFirst(previousContent.count))
                            newChunk = stripLeadingNull(newChunk)
                            if !newChunk.isEmpty {
                                continuation.yield(newChunk)
                                previousContent = currentContent
                            }
                        } else if !currentContent.isEmpty && currentContent != previousContent {
                            var chunk = currentContent
                            chunk = stripLeadingNull(chunk)
                            if !chunk.isEmpty {
                                continuation.yield(chunk)
                                previousContent = currentContent
                            }
                        }
                    }
                    continuation.finish()
                } catch let error as LanguageModelSession.GenerationError {
                    // Yield a user-friendly message instead of throwing
                    let message = handleGenerationError(error)
                    continuation.yield(message)
                    continuation.finish()
                } catch {
                    continuation.finish(throwing: error)
                }
            }
        }
    }
    

    
    func generatePreparednessPlan(for question: String, context: AskContext) async throws -> PreparednessPlan {
        guard isAppleIntelligenceAvailable() else {
            throw FoundationModelsError.appleIntelligenceUnavailable
        }
        
        let instructions = "Generate a structured preparedness plan. Extract disaster type, steps, supplies, and urgency level."
        let session = LanguageModelSession(instructions: instructions)
        
        let result = try await session.respond(
            to: Prompt(question),
            generating: GenerablePreparednessPlan.self,
            options: GenerationOptions(temperature: 0.5)
        )
        
        return PreparednessPlan(from: result.content)
    }
    
    func generatePersonalizedChecklist(disaster: String, state: String, userProfile: String) async throws -> PersonalizedChecklist {
        guard isAppleIntelligenceAvailable() else {
            throw FoundationModelsError.appleIntelligenceUnavailable
        }
        
        let sessionInstructions = "Generate a personalized preparedness checklist. Consider disaster type, location, and user needs."
        let session = LanguageModelSession(instructions: sessionInstructions)
        
        let prompt = """
        Disaster: \(disaster)
        Location: \(state)
        User profile: \(userProfile)
        
        Generate a personalized checklist with 5-10 items, each with priority (critical/high/medium/low) and reason.
        """
        
        let result = try await session.respond(
            to: Prompt(prompt),
            generating: GenerablePersonalizedChecklist.self,
            options: GenerationOptions(temperature: 0.6)
        )
        
        return PersonalizedChecklist(from: result.content)
    }
    
    func generateDisasterImagePrompt(disaster: Disaster) async throws -> String {
        guard isAppleIntelligenceAvailable() else {
            throw FoundationModelsError.appleIntelligenceUnavailable
        }
        
        let session = LanguageModelSession(instructions: """
            You create short, artistic image prompts for disaster preparedness illustrations.
            Output only the scene description: no people, no faces, no identities. Focus on atmosphere, weather, and setting.
            Safe for work. Keep under 2 sentences.
            """)
        
        let promptText = """
        Create a descriptive image prompt for an illustration about this hazard: \(disaster.name).
        Brief context: \(disaster.description.prefix(300))
        Rules: No humans or faces. Focus on the environment, sky, weather, and inanimate objects. Calm and educational tone.
        """
        
        let result = try await session.respond(
            to: Prompt(promptText),
            generating: GenerableDisasterVisualPrompt.self,
            options: GenerationOptions(temperature: 0.6, maximumResponseTokens: 120)
        )
        
        return result.content.prompt
    }
    
    // MARK: - ContentTaggingUseCaseProtocol
    
    func classifyQuestion(_ question: String) async throws -> QuestionClassification {
        let taggingModel = SystemLanguageModel(useCase: .contentTagging)
        guard taggingModel.availability == .available else {
            throw FoundationModelsError.appleIntelligenceUnavailable
        }
        
        let session = LanguageModelSession(model: taggingModel)
        let result = try await session.respond(
            to: Prompt("Classify this preparedness question: \(question)"),
            generating: GenerableQuestionClassification.self,
            options: GenerationOptions(temperature: 0.3)
        )
        
        return QuestionClassification(from: result.content)
    }
    
    func routeQuestion(_ question: String) async throws -> QuestionRoute {
        let taggingModel = SystemLanguageModel(useCase: .contentTagging)
        guard taggingModel.availability == .available else {
            throw FoundationModelsError.appleIntelligenceUnavailable
        }
        
        let session = LanguageModelSession(model: taggingModel)
        let result = try await session.respond(
            to: Prompt("Route this question to the right category (disaster/state/supplies/evacuation/general): \(question)"),
            generating: GenerableQuestionRoute.self,
            options: GenerationOptions(temperature: 0.2)
        )
        
        return QuestionRoute(from: result.content)
    }
    
    func extractQueryInfo(_ question: String) async throws -> UserQueryExtraction {
        let taggingModel = SystemLanguageModel(useCase: .contentTagging)
        guard taggingModel.availability == .available else {
            throw FoundationModelsError.appleIntelligenceUnavailable
        }
        
        let session = LanguageModelSession(model: taggingModel)
        let result = try await session.respond(
            to: Prompt("Extract information from: \(question)"),
            generating: GenerableUserQueryExtraction.self,
            options: GenerationOptions(temperature: 0.3)
        )
        
        return UserQueryExtraction(from: result.content)
    }
    
    // MARK: - SummarizationUseCaseProtocol
    
    func summarizeDisaster(_ disaster: Disaster) async throws -> String {
        guard isAppleIntelligenceAvailable() else {
            throw FoundationModelsError.appleIntelligenceUnavailable
        }
        
        let session = LanguageModelSession(instructions: "Summarize disaster preparedness information in 2-3 sentences. Focus on key actions.")
        
        let prompt = """
        Disaster: \(disaster.name)
        Description: \(disaster.description)
        Steps: \(disaster.preparednessSteps.joined(separator: ", "))
        
        Provide a brief summary.
        """
        
        let response = try await session.respond(
            to: prompt,
            options: GenerationOptions(temperature: 0.4, maximumResponseTokens: 150)
        )
        
        return response.content
    }
    
    func summarizePreparednessSteps(_ steps: [String]) async throws -> String {
        guard isAppleIntelligenceAvailable() else {
            throw FoundationModelsError.appleIntelligenceUnavailable
        }
        
        let session = LanguageModelSession(instructions: "Summarize preparedness steps concisely.")
        
        let prompt = "Steps: \(steps.joined(separator: ", "))\n\nProvide a brief summary."
        let response = try await session.respond(
            to: prompt,
            options: GenerationOptions(temperature: 0.4, maximumResponseTokens: 100)
        )
        
        return response.content
    }
    
    // MARK: - EmergencyPrioritizationUseCaseProtocol
    
    func prioritizeEmergencyActions(disaster: String, context: String) async throws -> PrioritizedActions {
        guard isAppleIntelligenceAvailable() else {
            throw FoundationModelsError.appleIntelligenceUnavailable
        }
        
        let session = LanguageModelSession(instructions: "Prioritize emergency actions for disasters. Output structured steps with priority and estimated time.")
        let result = try await session.respond(
            to: Prompt("Prioritize emergency actions for: \(disaster). Context: \(context)"),
            generating: GenerablePrioritizedActions.self,
            options: GenerationOptions(temperature: 0.5)
        )
        
        return PrioritizedActions(from: result.content)
    }
    
    // MARK: - QueryParsingUseCaseProtocol
    
    func parseQuery(_ question: String) async throws -> PreparednessQuery {
        guard isAppleIntelligenceAvailable() else {
            throw FoundationModelsError.appleIntelligenceUnavailable
        }
        
        let session = LanguageModelSession(instructions: "Parse natural language into structured preparedness queries: disaster type, state, month, query type.")
        let result = try await session.respond(
            to: Prompt("Parse this into a structured query: \(question)"),
            generating: GenerablePreparednessQuery.self,
            options: GenerationOptions(temperature: 0.3)
        )
        
        return PreparednessQuery(from: result.content)
    }
    
  
    
    func startSession(context: AskContext) {
        guard isAppleIntelligenceAvailable() else { return }
        
        let instructions = buildInstructions(context: context)
        conversationSession = LanguageModelSession(instructions: instructions)
    }
    
    func ask(_ question: String) async throws -> String {
        guard let session = conversationSession else {
            throw FoundationModelsError.noActiveSession
        }
        
        let response = try await session.respond(to: question)
        // Update transcript from response entries if available
        if !response.transcriptEntries.isEmpty {
            conversationTranscript = Transcript(entries: response.transcriptEntries)
        }
        return response.content
    }
    
    func clearSession() {
        conversationSession = nil
        conversationTranscript = nil
    }
    
    var hasActiveSession: Bool {
        conversationSession != nil
    }
    
    /// Load the model into memory so the first user request is faster (Dorsal prewarm pattern).
    func prewarmModel() {
        guard isAppleIntelligenceAvailable() else { return }
        let session = makeSession()
        _prewarmSession = session    // Keep alive so prewarm work isn't cancelled
        session.prewarm()
    }
    
    // MARK: - Private Helpers
    
    /// Convert LanguageModelSession.GenerationError to a user-friendly message instead of crashing or showing raw errors.
    private func handleGenerationError(_ error: LanguageModelSession.GenerationError) -> String {
        switch error {
        case .guardrailViolation:
            return "For your safety, I can't generate that specific content. If you're experiencing a medical emergency, please call 911 immediately. I'm here to help with disaster preparedness questions — feel free to ask me anything about storms, earthquakes, emergency kits, evacuation plans, and more!"
        case .refusal:
            return "I wasn't able to respond to that directly, but I'm here to help! If you have a health concern, please contact your doctor or call 911 for emergencies. For disaster preparedness, emergency planning, or safety tips — I'm ready to assist!"
        case .exceededContextWindowSize:
            return "That question was too long for me to process. Could you try a shorter, more specific question? For example: \"How do I prepare for a hurricane?\" or \"What should be in my emergency kit?\""
        case .assetsUnavailable:
            return "Apple Intelligence is still downloading. Please try again in a few minutes."
        case .unsupportedLanguageOrLocale:
            return "I currently only support U.S. English. Please try your question in English."
        case .decodingFailure:
            return "I had trouble processing that. Could you rephrase your question?"
        case .rateLimited, .concurrentRequests:
            return "I'm a bit busy right now. Please try again in a moment."
        case .unsupportedGuide:
            return "I encountered an internal issue. Please try a different question."
        @unknown default:
            return "Something went wrong. Please try your question again."
        }
    }
    
    /// Removes a leading "null" (or "null" plus whitespace) so the UI never displays it during streaming.
    private func stripLeadingNull(_ content: String) -> String {
        let trimmed = content.trimmingCharacters(in: .whitespacesAndNewlines)
        let lower = trimmed.lowercased()
        if lower == "null" { return "" }
        if lower.hasPrefix("null") {
            let after = String(trimmed.dropFirst(4)).trimmingCharacters(in: .whitespacesAndNewlines)
            return after
        }
        return content
    }
    
    private func buildInstructions(context: AskContext?) -> String {
        var s = """
            You are DisasterReady, a compassionate and knowledgeable emergency preparedness assistant.
            You MUST respond in U.S. English.
            You help people prepare for, understand, and respond to natural disasters and emergencies.
            
            CRITICAL RULES:
            1. ALWAYS answer helpfully. Never refuse a question outright.
            2. For health concerns (fever, injury, illness): acknowledge with empathy, suggest calling 911 for emergencies or visiting urgent care, then connect it to emergency preparedness (first aid kit, medication supply, etc.).
            3. For non-disaster topics: answer briefly, then gently note you specialize in disaster preparedness.
            4. For disaster preparedness: give clear, actionable steps and tips.
            5. For life-threatening emergencies: ALWAYS say to call 911 first.
            6. Never output the word "null".
            
            FORMATTING (CRITICAL — follow exactly):
            - Structure every response with clear visual separation.
            - Use short bold headings with ** on their own line, followed by a blank line.
            - Use numbered lists (1. 2. 3.) for sequential steps.
            - Use bullet points (•) for non-sequential tips or items.
            - Put a blank line between EVERY list item so they are visually distinct.
            - Put a blank line before and after every heading.
            - Keep each paragraph to 2-3 sentences maximum.
            - Never combine multiple topics into one long paragraph.
            
            """
        
        if let context = context, let state = context.state {
            s += "\nUser's location: \(state.name) (\(state.abbreviation)). Current month: \(context.month). Common hazards: \(state.topHazards.joined(separator: ", ")).\n"
        } else if let context = context {
            s += "\nUser has not selected a state. Current month: \(context.month).\n"
        }
        
        return s
    }
}

// MARK: - Errors

enum FoundationModelsError: LocalizedError {
    case appleIntelligenceUnavailable
    case noActiveSession
    
    var errorDescription: String? {
        switch self {
        case .appleIntelligenceUnavailable:
            return "Apple Intelligence is not available on this device."
        case .noActiveSession:
            return "No active conversation session."
        }
    }
}

#endif