// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "DisasterReady",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "DisasterReady",
            targets: ["AppModule"],
            bundleIdentifier: "Priyanka.DisasterReady",
            teamIdentifier: "7SWZXF52TC",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .weather
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)